name: anima
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  url_launcher: ^6.0.20
  flutter_svg: ^1.0.0
  provider: ^6.0.0
  http: ^0.13.3
  dotted_border: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^4.1.1
  build_runner: ^2.3.0


flutter_intl:
  enabled: true

flutter:
  uses-material-design: true

  assets:
    - assets/pick/sign_in.svg
    - assets/pick/fingerprint.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf